name: mbloader autobuild
on:
 push:
  branches: [ "main" ]
pull_request: 
 branches: [ "main" ]
jobs:
 build:
  runs-on: ubuntu-latest
steps:
 - uses: actions/checkout@v4
 - name: Setup JDK 21
 -uses: actions/setup-java@v4
   with:
   java-version: '17'
   distribution: 'temurin'
 - name: Grant execution permissions
    run: chmod +x gradlew
 - name: Build
    run: ./gradlew build --warning-mode=all -stacktrace